# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: 886697164571.dkr.ecr.ap-southeast-1.amazonaws.com/base_image:v2

before_script:
  - echo "Before script section"


after_script:
  - echo "After script section"

stages:
- test
- build
- deploy

test1:
  stage: test
  image: 886697164571.dkr.ecr.ap-southeast-1.amazonaws.com/base_image:v5_sonar
  script:
    - echo "Do a test here"
    - /usr/sonar-scanner-4.6.0.2311-linux/bin/sonar-scanner -Dsonar.host.url=${sonar_url} -Dsonar.login=${sonar_token}  -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.projectKey=devsecops_app1 -Dsonar.sources=./
  tags:
    - dev
  only:
    - master

test2:
  stage: test
  image: 886697164571.dkr.ecr.ap-southeast-1.amazonaws.com/base_image:v5_sonar
  script:
    - echo "Do a test here just for merge request"
    - /usr/sonar-scanner-4.6.0.2311-linux/bin/sonar-scanner -Dsonar.host.url=${sonar_url} -Dsonar.login=${sonar_token}  -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.projectKey=devsecops_app1 -Dsonar.sources=./
  tags:
    - dev
  only:
    - merge_requests

build1:
  stage: build
  script:
    - echo "Do your build here"
    - docker build -t helloworld:v3 .
  tags:
    - dev
  when: manual
  only:
    - master


deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
    - aws configure set aws_access_key_id $aws_ci_AK
    - aws configure set aws_secret_access_key $aws_ci_SK
    - aws configure set default.region $region
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 886697164571.dkr.ecr.ap-southeast-1.amazonaws.com
    - docker tag helloworld:v3 886697164571.dkr.ecr.ap-southeast-1.amazonaws.com/${repo_name}:${tag}
    - docker push 886697164571.dkr.ecr.ap-southeast-1.amazonaws.com/${repo_name}:${tag}

  tags:
    - dev
  when: manual
  only:
    - master

